# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20180424_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('post_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_by', to='firstapp.User')),
            ],
        ),
    ]
