# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_quotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='post_by',
        ),
        migrations.AddField(
            model_name='quotes',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='firstapp.User'),
        ),
    ]
