# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_quotes_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to='firstapp.User'),
        ),
    ]
